  /*let ImgArr = JSON.stringify([
]);*/
  let ImgArr = [{
      'place': 'Tableware',
      'img': 'Plate.png'
    }, {
      'place': 'Meal/Omelette',
      'img': 'Pig.png'
    }, {
      'place': 'Meal/Omelette',
      'img': 'Egg.png'
    }, {
      'place': 'Meal/Omelette',
      'img': 'Green1.png'
    }, {
      'place': 'Meal/Omelette',
      'img': 'Tomato.png'
    }, {
      'place': 'Meal/Pasta1',
      'img': 'Pasta1.png'
    }, {
      'place': 'Meal/Pasta1',
      'img': 'Tomato.png'
    }, {
      'place': 'Meal/Pasta1',
      'img': 'Green2.png'
    }, {
      'place': 'Meal/Pasta1',
      'img': 'Chees.png'
    }, {
      'place': 'Shop',
      'img': 'Apple1.png',
      'scale': 2
    },
    //  {
    //   'place': 'Shop',
    //   'img': 'Apple2.png',
    //   'scale': 2
    // },
    {
      'place': 'Shop',
      'img': 'Broccoli.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Cabbage.png',
      'scale': 1.5
    }, {
      'place': 'Shop',
      'img': 'Carrot.png',
      'scale': 0.8
    }, {
      'place': 'Shop',
      'img': 'Chiken.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Corn.png',
      'scale': 2
    }, {
      'place': 'Shop',
      'img': 'Cucumber.png',
      'scale': 1.4
    }, {
      'place': 'Shop',
      'img': 'Egg1.png',
      'scale': 1
    },
    //  {
    //   'place': 'Shop',
    //   'img': 'Egg2.png',
    //   'scale': 1
    // },
    {
      'place': 'Shop',
      'img': 'Eggplant.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Limon.png',
      'scale': 1.5
    }, {
      'place': 'Shop',
      'img': 'Mushroom.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Onion.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Orange.png',
      'scale': 2
    }, {
      'place': 'Shop',
      'img': 'Pasta.png',
      'scale': 0.8
    }, {
      'place': 'Shop',
      'img': 'Pear.png',
      'scale': 1.5
    }, {
      'place': 'Shop',
      'img': 'Pepper.png',
      'scale': 1
    },
    //  {
    //   'place': 'Shop',
    //   'img': 'Pepper2.png',
    //   'scale': 2.4
    // },
    {
      'place': 'Shop',
      'img': 'Pig.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Potato.png',
      'scale': 0.8
    }, {
      'place': 'Shop',
      'img': 'Radish.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Green.png',
      'scale': 1.6
    }, {
      'place': 'Shop',
      'img': 'Strawberry.png',
      'scale': 3
    }, {
      'place': 'Shop',
      'img': 'Tomato.png',
      'scale': 0.8
    }, {
      'place': 'Shop',
      'img': 'Watermelon.png',
      'scale': 2
    }, {
      'place': 'Shop',
      'img': 'Chees.png',
      'scale': 1
    }, {
      'place': 'Shop',
      'img': 'Basket.png'
    }, {
      'place': 'Shop',
      'img': 'Shop_main.png'
    }, {
      'place': 'Shop',
      'img': 'Plane1.png'
    }, {
      'place': 'Shop',
      'img': 'Plane2.png'
    }, {
      'place': 'Shop',
      'img': 'Дно_Ящик_1.png'
    }, {
      'place': 'Shop',
      'img': 'Перед_Ящик_1.png'
    }, {
      'place': 'Shop',
      'img': 'Рамка_Ящик_1.png'
    }, {
      'place': 'Shop',
      'img': 'Дно_Ящик_2.png'
    }, {
      'place': 'Shop',
      'img': 'Перед_Ящик_2.png'
    }, {
      'place': 'Shop',
      'img': 'Рамка_Ящик_2.png'
    }, {
      'place': 'Kitchen',
      'img': 'Apron.png'
    }, {
      'place': 'Kitchen',
      'img': 'Board1.png'
    }, {
      'place': 'Kitchen',
      'img': 'Board2.png'
    }, {
      'place': 'Kitchen',
      'img': 'Hat.png'
    }, {
      'place': 'Kitchen',
      'img': 'KitchenMain.png'
    }, {
      'place': 'Kitchen',
      'img': 'Knife1.png'
    }, {
      'place': 'Kitchen',
      'img': 'Pan1.png'
    }, {
      'place': 'Kitchen',
      'img': 'Pan2.png'
    }, {
      'place': 'Kitchen',
      'img': 'Pan3.png'
    }, {
      'place': 'Kitchen',
      'img': 'Pan4.png'
    }, {
      'place': 'Kitchen',
      'img': 'Plate1.png'
    }, {
      'place': 'Kitchen',
      'img': 'Plate2.png'
    }, {
      'place': 'Kitchen',
      'img': 'Plate3.png'
    }, {
      'place': 'Kitchen',
      'img': 'Sault.png'
    }, {
      'place': 'Kitchen',
      'img': 'Stove.png'
    }
  ];
